# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Claude's Blog
locale: en-GB
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Here you find everything you need to survive; coding, crazy projects, occasional
  travel info and product review. Only coffee is not included
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.claude.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: null
repository: reinhrst/reinhrst.github.io
github_username: reinhrst
defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      comments: true
comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"

author:
  name: 'Reinoud Elhorst (nick: Claude)'
  bio: 20+ years professional development experience in (mostly successful) startups; always working on hobby projects. Happy cyclist, SUPper, swimmer.
  avatar: /assets/images/bio.jpeg
  location: Haarlem, Netherlands
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ghp@claude.nl"
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://blog.claude.nl/"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/reinhrst"
    - label: Linkedin
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/reinoudelhorst/"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: dirt
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
